// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: grpc/proto/book_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookServiceClient interface {
	ServiceRegisterUser(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*BookStatusResponse, error)
	ServiceFindUserById(ctx context.Context, in *FindBookByIdRequest, opts ...grpc.CallOption) (*FindBookByIdRequest, error)
}

type bookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookServiceClient(cc grpc.ClientConnInterface) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) ServiceRegisterUser(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*BookStatusResponse, error) {
	out := new(BookStatusResponse)
	err := c.cc.Invoke(ctx, "/bookservice.BookService/ServiceRegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) ServiceFindUserById(ctx context.Context, in *FindBookByIdRequest, opts ...grpc.CallOption) (*FindBookByIdRequest, error) {
	out := new(FindBookByIdRequest)
	err := c.cc.Invoke(ctx, "/bookservice.BookService/ServiceFindUserById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServiceServer is the server API for BookService service.
// All implementations must embed UnimplementedBookServiceServer
// for forward compatibility
type BookServiceServer interface {
	ServiceRegisterUser(context.Context, *CreateBookRequest) (*BookStatusResponse, error)
	ServiceFindUserById(context.Context, *FindBookByIdRequest) (*FindBookByIdRequest, error)
	mustEmbedUnimplementedBookServiceServer()
}

// UnimplementedBookServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (UnimplementedBookServiceServer) ServiceRegisterUser(context.Context, *CreateBookRequest) (*BookStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceRegisterUser not implemented")
}
func (UnimplementedBookServiceServer) ServiceFindUserById(context.Context, *FindBookByIdRequest) (*FindBookByIdRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceFindUserById not implemented")
}
func (UnimplementedBookServiceServer) mustEmbedUnimplementedBookServiceServer() {}

// UnsafeBookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookServiceServer will
// result in compilation errors.
type UnsafeBookServiceServer interface {
	mustEmbedUnimplementedBookServiceServer()
}

func RegisterBookServiceServer(s grpc.ServiceRegistrar, srv BookServiceServer) {
	s.RegisterService(&BookService_ServiceDesc, srv)
}

func _BookService_ServiceRegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).ServiceRegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookservice.BookService/ServiceRegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).ServiceRegisterUser(ctx, req.(*CreateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_ServiceFindUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindBookByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).ServiceFindUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookservice.BookService/ServiceFindUserById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).ServiceFindUserById(ctx, req.(*FindBookByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookService_ServiceDesc is the grpc.ServiceDesc for BookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bookservice.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServiceRegisterUser",
			Handler:    _BookService_ServiceRegisterUser_Handler,
		},
		{
			MethodName: "ServiceFindUserById",
			Handler:    _BookService_ServiceFindUserById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/book_service.proto",
}
